# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a377a62ef4c9537dea8121d665752c087dbb1fa1edc22ed195b88132b3129d3c6f5044389e74c16fd1d4ee09366ba5d1cae84dc377c0754cd9c1d1f9298d6240

test:
  secret_key_base: aa4544992eb4fe231719d89eba12e4f04017fcba9435af7ca070b0d40643ced6fbac553c91b735d2ab41572b0fff849a8d395015985af1e9f9c0a68160829aff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
